name: H1B Slot Alert

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  check-slot:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v5


      - name: Run monitor

        env:

          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |

          pip install requests

          python monitor.py



      - name: Save dates

        run: |

          git config --global user.name "github-actions"

          git config --global user.email "github-actions@github.com"


          git add last_dates.txt


          git commit -m "Update dates" || echo "No changes"


          git push
